clearvars; close all; clc;


cd(fileparts(mfilename('fullpath')));
compPath = '../../COMPILED/driver/for_testing';
mkdir(compPath);

defaults2JSON;


mcc('-o', 'driver',...
    '-W', 'main:driver',...
    '-T', 'link:exe',...
    '-d', compPath,...
    '-R', '-logfile,execution.log',...
    '-v', './driver.m',...
    '-a', './+frame',...
    '-a', './+frame/DataFrame.m',...
    '-a', './+filter',...
    '-a', './+recon',...
    '-a', './+unmix',...
    '-a', './+util',...
    '-a', './collatePipelineOutput.m',...
    '-a', './defaultJSONPath.m',...
    '-a', './defaults2JSON.m',...
    '-a', './driveHDF5Writing.m',...
    '-a', './driveRecons.m',...
    '-a', './drivePreprocessing.m',...
    '-a', './driver.m',...
    '-a', './driveUnmixing.m',...
    '-a', './json',...
    '-a', './json/defaults',...
    '-a', './external',...
    '-a', './external/hdf5tools',...
    '-a', './external/msotbeans.jar',...
    '-a', './external/patbeans.jar',...
    '-a', './external/xbean.jar');

system(['mkdir -p ',fullfile(compPath,'json','defaults')]);
system(['cp -r ./json/defaults ',fullfile(compPath,'json')]);