clearvars; close all; clc;


cd(fileparts(mfilename('fullpath')));
mkdir('./COMPILED/driver/for_testing');

mcc -o driver...
    -W main:driver...
    -T link:exe...
    -d ./COMPILED/driver/for_testing...
    -R '-logfile,execution.log'...
    -v ./driver.m...
    -a ./+frame...
    -a ./+frame/DataFrame.m...
    -a ./+filter...
    -a ./+recon...
    -a ./+unmix...
    -a ./+util...
    -a ./collatePipelineOutput.m...
    -a ./defaultJSONPath.m...
    -a ./defaults2JSON.m...
    -a ./driveHDF5Writing.m...
    -a ./driveRecons.m...
    -a ./drivePreprocessing.m...
    -a ./driver.m...
    -a ./driveUnmixing.m...
    -a ./json...
    -a ./json/defaults...
    -a ./external...
    -a ./external/hdf5tools...
    -a ./external/msotbeans.jar...
    -a ./external/patbeans.jar...
    -a ./external/xbean.jar 
